# Workflow to send master to pypi and tag the branch
name: master to pypi with comments and tag

# Triggers the workflow on push to the master branch
on:
  push:
    branches: [ master ]

env:
  SCIPION_CANCEL_XMIPP_BINDING_WARNING: True

jobs:
  call-publish-workflow:
    uses: scipion-em/.github/.github/workflows/publish_and_tag_toml.yml@master
    with:
      folder: pwem
    secrets: inherit
